# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Mapache' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mapache
  pod 'SwiftyJSON', '~> 4.0'

  target 'MapacheTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapacheUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
